language: php
php:
    - 7.1
    - 7.0

matrix:
    fast_finish: true

install:
    - composer install
    - composer require satooshi/php-coveralls

script:
    - mkdir -p build/logs
    - composer travis-test

after_script:
    - php vendor/bin/coveralls
